<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\TujuanPencatatan;

class TujuanPencatatanSedder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
//         TujuanPencatatan::create(['ID_PENCATATAN'=>'84','ID_KODE_UNIT_KERJA'=>'1',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'84','ID_KODE_UNIT_KERJA'=>'2',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'84','ID_KODE_UNIT_KERJA'=>'3',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'85','ID_KODE_UNIT_KERJA'=>'4',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'86','ID_KODE_UNIT_KERJA'=>'5',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'87','ID_KODE_UNIT_KERJA'=>'6',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'88','ID_KODE_UNIT_KERJA'=>'7',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'89','ID_KODE_UNIT_KERJA'=>'8',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'90','ID_KODE_UNIT_KERJA'=>'9',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'91','ID_KODE_UNIT_KERJA'=>'10',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'92','ID_KODE_UNIT_KERJA'=>'11',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'93','ID_KODE_UNIT_KERJA'=>'12',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'94','ID_KODE_UNIT_KERJA'=>'13',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'95','ID_KODE_UNIT_KERJA'=>'14',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'96','ID_KODE_UNIT_KERJA'=>'15',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'97','ID_KODE_UNIT_KERJA'=>'16',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'98','ID_KODE_UNIT_KERJA'=>'17',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'99','ID_KODE_UNIT_KERJA'=>'18',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'100','ID_KODE_UNIT_KERJA'=>'19',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'101','ID_KODE_UNIT_KERJA'=>'20',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'102','ID_KODE_UNIT_KERJA'=>'21',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'103','ID_KODE_UNIT_KERJA'=>'22',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'104','ID_KODE_UNIT_KERJA'=>'1',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'105','ID_KODE_UNIT_KERJA'=>'2',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'106','ID_KODE_UNIT_KERJA'=>'3',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'107','ID_KODE_UNIT_KERJA'=>'4',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'108','ID_KODE_UNIT_KERJA'=>'5',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'109','ID_KODE_UNIT_KERJA'=>'6',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'110','ID_KODE_UNIT_KERJA'=>'7',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'111','ID_KODE_UNIT_KERJA'=>'8',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'112','ID_KODE_UNIT_KERJA'=>'9',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'113','ID_KODE_UNIT_KERJA'=>'10',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'114','ID_KODE_UNIT_KERJA'=>'11',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'115','ID_KODE_UNIT_KERJA'=>'12',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'116','ID_KODE_UNIT_KERJA'=>'13',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'117','ID_KODE_UNIT_KERJA'=>'14',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'118','ID_KODE_UNIT_KERJA'=>'15',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'119','ID_KODE_UNIT_KERJA'=>'16',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'120','ID_KODE_UNIT_KERJA'=>'17',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'121','ID_KODE_UNIT_KERJA'=>'18',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'122','ID_KODE_UNIT_KERJA'=>'19',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'123','ID_KODE_UNIT_KERJA'=>'20',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'124','ID_KODE_UNIT_KERJA'=>'21',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'125','ID_KODE_UNIT_KERJA'=>'22',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'126','ID_KODE_UNIT_KERJA'=>'1',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'127','ID_KODE_UNIT_KERJA'=>'2',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'128','ID_KODE_UNIT_KERJA'=>'3',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'129','ID_KODE_UNIT_KERJA'=>'4',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'130','ID_KODE_UNIT_KERJA'=>'5',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'131','ID_KODE_UNIT_KERJA'=>'6',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'132','ID_KODE_UNIT_KERJA'=>'7',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'133','ID_KODE_UNIT_KERJA'=>'8',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'134','ID_KODE_UNIT_KERJA'=>'9',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'135','ID_KODE_UNIT_KERJA'=>'10',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'136','ID_KODE_UNIT_KERJA'=>'11',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'137','ID_KODE_UNIT_KERJA'=>'12',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'138','ID_KODE_UNIT_KERJA'=>'13',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'139','ID_KODE_UNIT_KERJA'=>'14',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'140','ID_KODE_UNIT_KERJA'=>'15',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'141','ID_KODE_UNIT_KERJA'=>'16',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'142','ID_KODE_UNIT_KERJA'=>'17',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'143','ID_KODE_UNIT_KERJA'=>'18',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'144','ID_KODE_UNIT_KERJA'=>'19',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'145','ID_KODE_UNIT_KERJA'=>'20',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'146','ID_KODE_UNIT_KERJA'=>'21',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'147','ID_KODE_UNIT_KERJA'=>'22',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'148','ID_KODE_UNIT_KERJA'=>'1',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'149','ID_KODE_UNIT_KERJA'=>'2',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'150','ID_KODE_UNIT_KERJA'=>'3',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'151','ID_KODE_UNIT_KERJA'=>'4',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'152','ID_KODE_UNIT_KERJA'=>'5',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'153','ID_KODE_UNIT_KERJA'=>'6',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'154','ID_KODE_UNIT_KERJA'=>'7',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'155','ID_KODE_UNIT_KERJA'=>'8',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'156','ID_KODE_UNIT_KERJA'=>'9',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'157','ID_KODE_UNIT_KERJA'=>'10',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'158','ID_KODE_UNIT_KERJA'=>'11',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'159','ID_KODE_UNIT_KERJA'=>'12',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'160','ID_KODE_UNIT_KERJA'=>'13',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'161','ID_KODE_UNIT_KERJA'=>'14',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'162','ID_KODE_UNIT_KERJA'=>'15',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'163','ID_KODE_UNIT_KERJA'=>'16',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'164','ID_KODE_UNIT_KERJA'=>'17',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'165','ID_KODE_UNIT_KERJA'=>'18',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'166','ID_KODE_UNIT_KERJA'=>'19',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'167','ID_KODE_UNIT_KERJA'=>'20',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'168','ID_KODE_UNIT_KERJA'=>'21',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'169','ID_KODE_UNIT_KERJA'=>'22',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'170','ID_KODE_UNIT_KERJA'=>'1',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'171','ID_KODE_UNIT_KERJA'=>'2',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'172','ID_KODE_UNIT_KERJA'=>'3',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'173','ID_KODE_UNIT_KERJA'=>'4',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'174','ID_KODE_UNIT_KERJA'=>'5',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'175','ID_KODE_UNIT_KERJA'=>'6',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'176','ID_KODE_UNIT_KERJA'=>'7',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'177','ID_KODE_UNIT_KERJA'=>'8',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'178','ID_KODE_UNIT_KERJA'=>'9',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'179','ID_KODE_UNIT_KERJA'=>'10',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'180','ID_KODE_UNIT_KERJA'=>'11',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'181','ID_KODE_UNIT_KERJA'=>'12',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'182','ID_KODE_UNIT_KERJA'=>'13',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'183','ID_KODE_UNIT_KERJA'=>'14',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'184','ID_KODE_UNIT_KERJA'=>'15',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'185','ID_KODE_UNIT_KERJA'=>'16',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'186','ID_KODE_UNIT_KERJA'=>'17',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'187','ID_KODE_UNIT_KERJA'=>'18',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'188','ID_KODE_UNIT_KERJA'=>'19',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'189','ID_KODE_UNIT_KERJA'=>'20',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'190','ID_KODE_UNIT_KERJA'=>'21',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'191','ID_KODE_UNIT_KERJA'=>'22',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'192','ID_KODE_UNIT_KERJA'=>'22',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'193','ID_KODE_UNIT_KERJA'=>'1',]);
// TujuanPencatatan::create(['ID_PENCATATAN'=>'194','ID_KODE_UNIT_KERJA'=>'2',]);
//TujuanPencatatan::create(['ID_PENCATATAN'=>'194','ID_KODE_UNIT_KERJA'=>'2',]);
//TujuanPencatatan::create(['ID_PENCATATAN'=>'','ID_KODE_UNIT_KERJA'=>'',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'200','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'201','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'202','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'203','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'204','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'205','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'206','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'207','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'208','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'209','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'210','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'211','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'212','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'213','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'214','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'215','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'216','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'217','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'218','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'219','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'220','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'221','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'222','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'223','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'224','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'225','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'226','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'227','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'228','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'229','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'230','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'231','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'232','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'233','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'234','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'235','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'236','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'237','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'238','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'239','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'240','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'241','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'242','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'243','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'244','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'245','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'246','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'247','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'248','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'249','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'250','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'251','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'252','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'253','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'254','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'255','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'256','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'257','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'258','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'259','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'260','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'261','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'262','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'263','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'264','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'265','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'266','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'267','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'268','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'269','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'270','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'271','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'272','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'273','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'274','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'275','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'276','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'277','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'278','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'279','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'280','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'281','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'282','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'283','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'284','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'285','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'286','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'287','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'288','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'289','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'290','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'291','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'292','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'293','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'294','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'295','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'296','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'297','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'298','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'299','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'300','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'301','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'302','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'303','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'304','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'305','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'306','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'307','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'308','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'309','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'310','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'311','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'312','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'313','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'314','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'315','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'316','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'317','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'318','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'319','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'320','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'321','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'322','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'323','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'324','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'325','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'326','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'327','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'328','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'329','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'330','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'331','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'332','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'333','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'334','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'335','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'336','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'337','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'338','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'339','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'340','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'341','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'342','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'343','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'344','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'345','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'346','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'347','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'348','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'349','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'350','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'351','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'352','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'353','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'354','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'355','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'356','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'357','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'358','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'359','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'360','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'361','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'362','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'363','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'364','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'365','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'366','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'367','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'368','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'369','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'370','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'371','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'372','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'373','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'374','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'375','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'376','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'377','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'378','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'379','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'380','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'381','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'382','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'383','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'384','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'385','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'386','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'387','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'388','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'389','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'390','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'391','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'392','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'393','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'394','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'395','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'396','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'397','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'398','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'399','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'400','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'401','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'402','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'403','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'404','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'405','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'406','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'407','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'408','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'409','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'410','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'411','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'412','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'413','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'414','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'415','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'416','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'417','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'418','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'419','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'420','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'421','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'422','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'423','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'424','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'425','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'426','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'427','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'428','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'429','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'430','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'431','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'432','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'433','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'434','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'435','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'436','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'437','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'438','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'439','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'440','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'441','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'442','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'443','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'444','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'445','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'446','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'447','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'448','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'449','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'450','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'451','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'452','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'453','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'454','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'455','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'456','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'457','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'458','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'459','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'460','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'461','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'462','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'463','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'464','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'465','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'466','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'467','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'468','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'469','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'470','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'471','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'472','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'473','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'474','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'475','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'476','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'477','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'478','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'479','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'480','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'481','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'482','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'483','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'484','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'485','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'486','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'487','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'488','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'489','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'490','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'491','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'492','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'493','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'494','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'495','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'496','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'497','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'498','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'499','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'500','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'501','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'502','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'503','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'504','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'505','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'506','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'507','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'508','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'509','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'510','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'511','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'512','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'513','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'514','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'515','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'516','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'517','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'518','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'519','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'520','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'521','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'522','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'523','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'524','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'525','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'526','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'527','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'528','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'529','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'530','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'531','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'532','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'533','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'534','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'535','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'536','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'537','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'538','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'539','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'540','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'541','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'542','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'543','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'544','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'545','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'546','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'547','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'548','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'549','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'550','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'551','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'552','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'553','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'554','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'555','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'556','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'557','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'558','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'559','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'560','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'561','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'562','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'563','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'564','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'565','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'566','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'567','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'568','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'569','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'570','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'571','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'572','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'573','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'574','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'575','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'576','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'577','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'578','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'579','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'580','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'581','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'582','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'583','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'584','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'585','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'586','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'587','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'588','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'589','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'590','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'591','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'592','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'593','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'594','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'595','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'596','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'597','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'598','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'599','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'600','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'601','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'602','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'603','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'604','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'605','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'606','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'607','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'608','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'609','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'610','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'611','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'612','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'613','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'614','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'615','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'616','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'617','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'618','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'619','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'620','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'621','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'622','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'623','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'624','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'625','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'626','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'627','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'628','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'629','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'630','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'631','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'632','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'633','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'634','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'635','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'636','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'637','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'638','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'639','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'640','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'641','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'642','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'643','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'644','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'645','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'646','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'647','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'648','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'649','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'650','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'651','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'652','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'653','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'654','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'655','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'656','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'657','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'658','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'659','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'660','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'661','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'662','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'663','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'664','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'665','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'666','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'667','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'668','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'669','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'670','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'671','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'672','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'673','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'674','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'675','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'676','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'677','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'678','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'679','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'680','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'681','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'682','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'683','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'684','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'685','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'686','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'687','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'688','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'689','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'690','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'691','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'692','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'693','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'694','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'695','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'696','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'697','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'698','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'699','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'700','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'701','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'702','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'703','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'704','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'705','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'706','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'707','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'708','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'709','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'710','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'711','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'712','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'713','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'714','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'715','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'716','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'717','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'718','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'719','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'720','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'721','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'722','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'723','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'724','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'725','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'726','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'727','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'728','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'729','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'730','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'731','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'732','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'733','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'734','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'735','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'736','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'737','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'738','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'739','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'740','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'741','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'742','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'743','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'744','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'745','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'746','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'747','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'748','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'749','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'750','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'751','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'752','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'753','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'754','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'755','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'756','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'757','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'758','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'759','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'760','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'761','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'762','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'763','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'764','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'765','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'766','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'767','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'768','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'769','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'770','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'771','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'772','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'773','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'774','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'775','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'776','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'777','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'778','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'779','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'780','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'781','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'782','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'783','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'784','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'785','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'786','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'787','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'788','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'789','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'790','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'791','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'792','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'793','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'794','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'795','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'796','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'797','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'798','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'799','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'800','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'801','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'802','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'803','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'804','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'805','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'806','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'807','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'808','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'809','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'810','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'811','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'812','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'813','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'814','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'815','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'816','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'817','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'818','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'819','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'820','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'821','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'822','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'823','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'824','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'825','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'826','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'827','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'828','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'829','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'830','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'831','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'832','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'833','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'834','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'835','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'836','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'837','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'838','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'839','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'840','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'841','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'842','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'843','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'844','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'845','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'846','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'847','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'848','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'849','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'850','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'851','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'852','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'853','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'854','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'855','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'856','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'857','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'858','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'859','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'860','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'861','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'862','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'863','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'864','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'865','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'866','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'867','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'868','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'869','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'870','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'871','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'872','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'873','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'874','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'875','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'876','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'877','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'878','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'879','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'880','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'881','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'882','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'883','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'884','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'885','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'886','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'887','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'888','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'889','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'890','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'891','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'892','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'893','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'894','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'895','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'896','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'897','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'898','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'899','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'900','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'901','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'902','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'903','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'904','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'905','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'906','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'907','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'908','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'909','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'910','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'911','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'912','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'913','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'914','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'915','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'916','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'917','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'918','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'919','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'920','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'921','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'922','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'923','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'924','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'925','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'926','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'927','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'928','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'929','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'930','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'931','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'932','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'933','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'934','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'935','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'936','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'937','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'938','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'939','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'940','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'941','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'942','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'943','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'944','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'945','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'946','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'947','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'948','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'949','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'950','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'951','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'952','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'953','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'954','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'955','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'956','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'957','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'958','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'959','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'960','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'961','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'962','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'963','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'964','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'965','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'966','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'967','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'968','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'969','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'970','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'971','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'972','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'973','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'974','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'975','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'976','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'977','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'978','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'979','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'980','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'981','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'982','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'983','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'984','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'985','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'986','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'987','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'988','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'989','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'990','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'991','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'992','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'993','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'994','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'995','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'996','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'997','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'998','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'999','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1000','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1001','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1002','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1003','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1004','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1005','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1006','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1007','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1008','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1009','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1010','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1011','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1012','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1013','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1014','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1015','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1016','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1017','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1018','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1019','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1020','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1021','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1022','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1023','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1024','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1025','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1026','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1027','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1028','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1029','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1030','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1031','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1032','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1033','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1034','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1035','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1036','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1037','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1038','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1039','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1040','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1041','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1042','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1043','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1044','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1045','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1046','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1047','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1048','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1049','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1050','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1051','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1052','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1053','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1054','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1055','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1056','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1057','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1058','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1059','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1060','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1061','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1062','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1063','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1064','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1065','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1066','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1067','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1068','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1069','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1070','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1071','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1072','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1073','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1074','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1075','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1076','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1077','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1078','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1079','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1080','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1081','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1082','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1083','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1084','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1085','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1086','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1087','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1088','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1089','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1090','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1091','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1092','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1093','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1094','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1095','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1096','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1097','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1098','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1099','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1100','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1101','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1102','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1103','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1104','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1105','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1106','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1107','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1108','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1109','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1110','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1111','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1112','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1113','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1114','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1115','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1116','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1117','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1118','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1119','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1120','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1121','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1122','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1123','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1124','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1125','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1126','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1127','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1128','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1129','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1130','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1131','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1132','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1133','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1134','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1135','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1136','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1137','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1138','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1139','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1140','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1141','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1142','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1143','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1144','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1145','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1146','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1147','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1148','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1149','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1150','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1151','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1152','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1153','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1154','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1155','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1156','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1157','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1158','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1159','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1160','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1161','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1162','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1163','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1164','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1165','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1166','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1167','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1168','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1169','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1170','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1171','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1172','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1173','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1174','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1175','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1176','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1177','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1178','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1179','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1180','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1181','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1182','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1183','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1184','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1185','ID_KODE_UNIT_KERJA'=>'16',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1186','ID_KODE_UNIT_KERJA'=>'17',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1187','ID_KODE_UNIT_KERJA'=>'18',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1188','ID_KODE_UNIT_KERJA'=>'19',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1189','ID_KODE_UNIT_KERJA'=>'20',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1190','ID_KODE_UNIT_KERJA'=>'21',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1191','ID_KODE_UNIT_KERJA'=>'22',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1192','ID_KODE_UNIT_KERJA'=>'1',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1193','ID_KODE_UNIT_KERJA'=>'2',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1194','ID_KODE_UNIT_KERJA'=>'3',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1195','ID_KODE_UNIT_KERJA'=>'4',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1196','ID_KODE_UNIT_KERJA'=>'5',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1197','ID_KODE_UNIT_KERJA'=>'6',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1198','ID_KODE_UNIT_KERJA'=>'7',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1199','ID_KODE_UNIT_KERJA'=>'8',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1200','ID_KODE_UNIT_KERJA'=>'9',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1201','ID_KODE_UNIT_KERJA'=>'10',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1202','ID_KODE_UNIT_KERJA'=>'11',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1203','ID_KODE_UNIT_KERJA'=>'12',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1204','ID_KODE_UNIT_KERJA'=>'13',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1205','ID_KODE_UNIT_KERJA'=>'14',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1206','ID_KODE_UNIT_KERJA'=>'15',]);
TujuanPencatatan::create(['ID_PENCATATAN'=>'1207','ID_KODE_UNIT_KERJA'=>'16',]);

    }
}
